const homeStyles = {
  main: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  boxTable: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    border: "1px solid #333",
    borderRadius: "2rem",
    paddingBottom: "1rem",
  },
  boxHeader: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ADD8E6",
    padding: "1rem",
    borderBottom: "1px solid black",
    borderRadius: "2rem",
    width: "100%",
    marginBottom: "1rem",
  },
  headerText: {
    color: "#333",
    textAlign: "center",
  },
  boxBody: {
    display: "flex",
    overflow: "auto",
    height: "300px",
    width: "800px",
  },
  itemBox: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    minHeight: "150px",
    width: "100%",
    backgroundColor: "#f0f0f0",
    borderRadius: "1rem",
  },
  itemText: {
    color: "#333",
    textAlign: "center",
  },
  loading: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
  },
  addButton: {
    backgroundColor: "#FF7F7F",
    border: "2px solid #FF7F7F",
    marginBottom: "1rem",
    padding: "1rem",
    height: "2rem",
    width: "2rem",
    boxSizing: "content-box",
    fontSize: "medium",
    fontWeight: "bold",
  },
  modal: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: 400,
    borderRadius: "1rem",
    backgroundColor: "white",
    color: "black",
    border: "2px solid #000",
    boxShadow: 24,
    padding: 4,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  modalForm: {
    display: "flex",
    gap: 2,
  },
  modalFormInput: {
    // color: "white",
    // backgroundColor: "gray",
    // borderColor: "white",
  },
};

export default homeStyles;
